// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCsWCZ7IY52gXPMgaK94nSkdLoHoa2xA4',
    appId: '1:122128999480:web:e146bbdced1232bf3132cd',
    messagingSenderId: '122128999480',
    projectId: 'fa21-bcs-130',
    authDomain: 'fa21-bcs-130.firebaseapp.com',
    storageBucket: 'fa21-bcs-130.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqpF8ksMVGV_LWMltwfTJ_BIg32nsNeQ0',
    appId: '1:122128999480:android:ea7330f22ccd2d073132cd',
    messagingSenderId: '122128999480',
    projectId: 'fa21-bcs-130',
    storageBucket: 'fa21-bcs-130.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ZpAFrngWW0SPJSxMLUl0aGKCRRqZn0A',
    appId: '1:122128999480:ios:58e746e30173bfd63132cd',
    messagingSenderId: '122128999480',
    projectId: 'fa21-bcs-130',
    storageBucket: 'fa21-bcs-130.firebasestorage.app',
    iosBundleId: 'com.example.databaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ZpAFrngWW0SPJSxMLUl0aGKCRRqZn0A',
    appId: '1:122128999480:ios:58e746e30173bfd63132cd',
    messagingSenderId: '122128999480',
    projectId: 'fa21-bcs-130',
    storageBucket: 'fa21-bcs-130.firebasestorage.app',
    iosBundleId: 'com.example.databaseSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCsWCZ7IY52gXPMgaK94nSkdLoHoa2xA4',
    appId: '1:122128999480:web:777e6e97f68b71473132cd',
    messagingSenderId: '122128999480',
    projectId: 'fa21-bcs-130',
    authDomain: 'fa21-bcs-130.firebaseapp.com',
    storageBucket: 'fa21-bcs-130.firebasestorage.app',
  );
}
